### ISSUE TITLE
Investigate the best way to generate Sphinx document from C header

### ISSUE THREAD

**Issue by hyunsik** [furiosa-ai/furiosa-sdk#17]
## Background
Currently, we are using Doxygen (https://www.doxygen.nl/index.html) to generate C reference document. Please visit the generated C reference at https://furiosa-ai.github.io/renegade-manual/references/nux/. Like pdoc3 issue, the page also looks different from our official documentation at https://furiosa-ai.github.io/renegade-manual/sdk/latest/ko/ generated by Sphinx (https://www.sphinx-doc.org).

## What we should do
The ultimate goal is to generate Sphinx documents for C reference. Please investigate if there is a way to generate Sphinx documents for C reference. If it's not possible, please find alternative way like bridging between Doxygen and Sphinx. It would be great if someone does some experiments with our C header and show how it works. 

The following articles are what I've found so far:
* https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/
* https://breathe.readthedocs.io/en/latest/

**Comment by JustinHMKim** [comment]
Here's an example of using Breathe to bridge Doxygen and Sphinx to generate a reference document for nux.h. It needs some cleaning up, but it does give a demo of it working. 
https://justinhmkim.github.io/furiosa-sdk/index.html

The above was generated with the below. 
https://github.com/JustinHMKim/furiosa-sdk/tree/cpp-sphinx-doc/cpp

**Comment by hyunsik** [comment]
@JustinHMKim Even though it's a demo work, It looks good to me. If we can tweak some parts like the no space bewtween the return type and funcation name, we will be able to use this work directly. Could you try to investigate ways to tweak some ugly parts?

Also, can we change the title 'Documentation' to Reference?
https://justinhmkim.github.io/furiosa-sdk/index.html#documentation

**Comment by JustinHMKim** [comment]
The spacing seems to be an issue with the sphinx_rtd_theme CSS when it deals with cpp, based on a couple of issue threads. 
https://github.com/readthedocs/sphinx_rtd_theme/issues/694
I'm looking into it though.

**Comment by hyunsik** [comment]
@JustinHMKim Could you submit PR too? After I check your PR, I'll give you some suggestion.

**Comment by JustinHMKim** [comment]
Okay, I've gone ahead and done so.
